### ISSUE TITLE
Track "administrative owner" as part of boundaries

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/geospatial-vector-veracity#100]
It'd be great to track the administrative "owner" of a polygon.  This would mean that we could link out to whatever agency/entity might have jurisdiction in some fashion over a pixel.  Needs more thinking + design, but worth pondering.

**Comment by charparr** [comment]
IMO there are far, far too too many agencies, corporations, and levels of government + administration to track this effectively in this repo. The way to do this would just be to fire off `INTERSECTS` query between the point and the stack of candidate polygon features.
