### ISSUE TITLE
Monitor place name change for point location AK370

### ISSUE THREAD

**Issue by charparr** [ua-snap/geospatial-vector-veracity#14]
Monitor place name change for point location `AK370` per guidance from Dept. of Interior.

**Comment by charparr** [comment]
See the Sq_ replacement names released today by DoI:

https://edits.nationalmap.gov/apps/gaz-domestic/public/all-official-sq-names

Cmd+F for Alaska. There are 26 places, and I believe none of them are present in our curated list of communities (they are mostly streams, creeks, summits, etc.).

Because `AK370` is not in this list as far as I can tell, I think just striking that place from the repo is the right move.
@MikeDelue thoughts?

**Comment by MikeDelue** [comment]
Agreed. Thanks for keeping an eye on this @charparr! AK370 shouldn't be in our point locations list anyway. There is a nearby point which may still be inhabited (Pop. ~1?) but is covered as AK416 Unga/	Uĝnaasaqax̂

I support striking AK370 from the list.
