### ISSUE TITLE
Sync presence  / absence and orthography of AK Indigenous names with ANLC list and guidance

### ISSUE THREAD

**Issue by charparr** [ua-snap/geospatial-vector-veracity#28]
Determine how many places in AK we currently have an 'alternative name' for that we would lose if we narrow back down to the ANLC list. If the number is large and regionally focused (say the ANLC is light on Tlingit & Haida names as an example) then we can have it as a goal to look for a trusted source to fill that gap. If it's a small number of names, or a large number but geographically dispersed then we can just wait for the linguists to solidify their positions on those place names and incorporate them when they become available.

**Comment by brucecrevensten** [comment]
Maybe we update the title of this to "Sync with Alaska Native language center list", etc.

**Comment by charparr** [comment]
Good with me! That tracks the ongoing email threads. What does "etc." mean in this context though?

**Comment by brucecrevensten** [comment]
Mainly, keeping the orthography correct, per the guidance we got.

**Comment by charparr** [comment]
Summary of where the ANLC Native name of record did **Not** match our record:

|     | ANLC Name       | ANLC Native name                            | alt_name                                     | B matches H            |
|----:|:----------------|:--------------------------------------------|:---------------------------------------------|:-----------------------|
|  12 | Anaktuvuk Pass  | Naqsraq, Anaqtuuvak                         | Anaqtuuvak / Naqsraq                         | Orthographic Exception |
|  21 | Arctic Village  | Vashrąįį K’o˛ o˛                            | Vashrąįį K'ǫǫ                                | Orthographic Exception |
|  22 | Atka            | At xˆ a xˆ                                  | Atx̂ax̂                                        | Orthographic Exception |
|  30 | Beaver          | Ts’aahudaaneekk’onh Denh                    | Ts'aahudaaneekk'onh Denh                     | Orthographic Exception |
|  31 | Belkofski       | Taxtamaxˆ                                   | Taxtamax̂                                     | Orthographic Exception |
|  60 | Chefornak       | Cevv’arneq / Caputnguaq                     | Cevvʼarneq / Caputnguaq                      | Slash Exception        |
|  63 | Chevak          | Cev’aq                                      | Cevʼaq                                       | Orthographic Exception |
|  72 | Chitina         | Tsedi Na’                                   | Tsedi Na'                                    | Orthographic Exception |
| 126 | False Pass      | Isanaxˆ                                     | Isanax̂                                       | Orthographic Exception |
| 141 | Golovin         | Cingik, Siŋik                               | Cingik / Siŋik                               | Slash Exception        |
| 154 | Holy Cross      | Ingirraller, Deloy Chet                     | Ingirraller / Deloy Chet                     | Slash Exception        |
| 156 | Hoonah          | Xunaa, Gaaw Yat’aḵ Aan                      | Xunaa / Gaaw Yat’aḵ Aan                      | Slash Exception        |
| 176 | Juneau          | Dzánti K’ihéeni                             | Dzánti K'ihéeni                              | Orthographic Exception |
| 199 | King Cove       | Agdaaĝuxˆ                                   | Agdaaĝux̂                                     | Orthographic Exception |
| 210 | Kodiak          | Sun’aq                                      | Sun'aq                                       | Orthographic Exception |
| 281 | Nikolski        | Chalukaxˆ                                   | Chalukax̂                                     | Orthographic Exception |
| 294 | Sheldons Point  | Nunam Iqua                                  | Sheldon Point                                | Order exception        |
| 304 | Paimute         | Paimiut                                     | Paimute                                      | Order exception        |
| 344 | St. George      | Anĝaaxchaluxˆ                               | Anĝaaxchalux̂                                 | Orthographic Exception |
| 347 | St. Paul        | Tanaxˆ Amixˆ                                | Tanax̂ Amix̂                                   | Orthographic Exception |
| 357 | Selawik         | Siiḷivik, Akuliġaq                          | Siiḷivik / Akuliġaq                          | Slash Exception        |
| 364 | Shungnak        | Isiŋnaq, Nuurviuraq                         | Isiŋnaq / Nuurviuraq                         | Slash Exception        |
| 380 | Stony River     | Gidighuyghatno’ Xidochagg Qay, K'qizaghetnu | Gidighuyghatno’ Xidochagg Qay / K'qizaghetnu | Slash Exception        |
| 386 | Takotna         | Tochotno'                                   | Tochotno’                                    | Orthographic Exception |
| 387 | Talkeetna       | K’dalkitnu                                  | K'dalkitnu                                   | Orthographic Exception |
| 388 | Tanacross       | Taats'altęy                                 | Taats’altęy                                  | Orthographic Exception |
| 391 | Tazlina         | Tezdlen Na'                                 | Tezdlen Na’                                  | Orthographic Exception |
| 396 | Tenakee Springs | Tʼanag̱eey, Tlaagoowu Aan                    | Tʼanag̱eey / Tlaagoowu Aan                    | Slash Exception        |
| 420 | Unalaska        | Iluuluxˆ                                    | Iluulux̂                                      | Orthographic Exception |
| 421 | Unga            | Uĝnaasaqaxˆ                                 | Uĝnaasaqax̂                                   | Orthographic Exception |
| 423 | Barrow          | Utqiaġvik                                   | Barrow                                       | Order exception        |

**Comment by charparr** [comment]
Summary of where the ANLC Native name of record and our record **DO** match.

|     | ANLC Name        | ANLC Native name            | alt_name                    |
|----:|:-----------------|:----------------------------|:----------------------------|
|   0 | Afognak          | Agw’aneq                    | Agw’aneq                    |
|   1 | Akhiok           | Kasukuak                    | Kasukuak                    |
|   2 | Akiachak         | Akiacuar                    | Akiacuar                    |
|   3 | Akiak            | Akiaq                       | Akiaq                       |
|   4 | Akutan           | Achan-ingiiga               | Achan-ingiiga               |
|   5 | Alakanuk         | Alarneq                     | Alarneq                     |
|   6 | Alatna           | Alaasuq                     | Alaasuq                     |
|   7 | Aleknagik        | Alaqnaqiq                   | Alaqnaqiq                   |
|  10 | Allakaket        | Aalaa Kkaakk’et             | Aalaa Kkaakk’et             |
|  11 | Ambler           | Ivisaappaat                 | Ivisaappaat                 |
|  14 | Anchorage        | Dgheyaytnu                  | Dgheyaytnu                  |
|  17 | Angoon           | Aangóon                     | Aangóon                     |
|  18 | Aniak            | Anyaraq                     | Anyaraq                     |
|  20 | Anvik            | Gitr’ingith Chagg           | Gitr’ingith Chagg           |
|  23 | Atmautluak       | Atmaulluaq                  | Atmaulluaq                  |
|  35 | Bethel           | Mamterilleq                 | Mamterilleq                 |
|  36 | Bettles          | Kk’odlel T’odegheelenh Denh | Kk’odlel T’odegheelenh Denh |
|  41 | Birch Creek      | Łiteet'aii                  | Łiteet'aii                  |
|  46 | Brevig Mission   | Sitaisaq                    | Sitaisaq                    |
|  47 | Buckland         | Kaŋiq                       | Kaŋiq                       |
|  49 | Cantwell         | Yidateni Na’                | Yidateni Na’                |
|  56 | Chalkyitsik      | Jałgiitsik                  | Jałgiitsik                  |
|  62 | Chenega          | Caniqaq                     | Caniqaq                     |
|  64 | Chickaloon       | Nay’dini’aa Na’             | Nay’dini’aa Na’             |
|  66 | Chignik          | Cirniq                      | Cirniq                      |
|  67 | Chignik Lagoon   | Nanwarnaq                   | Nanwarnaq                   |
|  68 | Chignik Lake     | Igyaraq                     | Igyaraq                     |
|  71 | Chistochina      | Tsiis Tl’edze’ Caegge       | Tsiis Tl’edze’ Caegge       |
|  74 | Chuathbaluk      | Curarpalek                  | Curarpalek                  |
|  76 | Circle           | Danzhit Khànląįį            | Danzhit Khànląįį            |
|  79 | Clarks Point     | Saguyaq                     | Saguyaq                     |
|  87 | Copper Center    | Tl’aticae’e                 | Tl’aticae’e                 |
|  90 | Craig            | Sháan Séet                  | Sháan Séet                  |
|  91 | Crooked Creek    | Qipcarpak                   | Qipcarpak                   |
|  93 | Deering          | Ipnatchiaq                  | Ipnatchiaq                  |
|  95 | Dillingham       | Curyung                     | Curyung                     |
|  96 | Little Diomede   | Iŋaliq                      | Iŋaliq                      |
|  97 | Dot Lake         | Kelt’aaddh Menn’            | Kelt’aaddh Menn’            |
| 101 | Eagle            | Tthee T'äwdlenn             | Tthee T'äwdlenn             |
| 106 | Eek              | Ekvicuaq                    | Ekvicuaq                    |
| 108 | Egegik           | Igyagiiq                    | Igyagiiq                    |
| 111 | Eklutna          | Idlughet                    | Idlughet                    |
| 113 | Ekwok            | Iquaq                       | Iquaq                       |
| 116 | Elim             | Neviarcaurluq               | Neviarcaurluq               |
| 118 | Emmonak          | Imangaq                     | Imangaq                     |
| 119 | English Bay      | Nanwalek                    | Nanwalek                    |
| 124 | Eyak             | Igya’aq                     | Igya’aq                     |
| 133 | Fort Yukon       | Gwichyaa Zheh               | Gwichyaa Zheh               |
| 135 | Gakona           | Ggax Kuna’                  | Ggax Kuna’                  |
| 136 | Galena           | Notaalee Denh               | Notaalee Denh               |
| 137 | Gambell          | Sivuqaq                     | Sivuqaq                     |
| 142 | Goodnews Bay     | Mamterat                    | Mamterat                    |
| 143 | Grayling         | Sixno' Xidakagg             | Sixno' Xidakagg             |
| 144 | Gulkana          | C'uul C'ena'                | C'uul C'ena'                |
| 146 | Haines           | Deishú                      | Deishú                      |
| 150 | Healy Lake       | Mendees Cheeg               | Mendees Cheeg               |
| 157 | Hooper Bay       | Naparyaarmiut               | Naparyaarmiut               |
| 160 | Hughes village   | Hut’odlee Kkaakk’et         | Hut’odlee Kkaakk’et         |
| 161 | Huslia           | Ts’aateyhdenaadekk’onh Denh | Ts’aateyhdenaadekk’onh Denh |
| 162 | Hydaburg         | Higdáa G̱ándlaay             | Higdáa G̱ándlaay             |
| 165 | Igiugig          | Igyaraq                     | Igyaraq                     |
| 167 | Iliamna          | Illiamna                    | Illiamna                    |
| 178 | Kake             | Ḵéex̱ʼ                       | Ḵéex̱ʼ                       |
| 180 | Kaktovik         | Qaaktuġvik                  | Qaaktuġvik                  |
| 181 | Kalifornsky      | Unhghenesditnu              | Unhghenesditnu              |
| 182 | Kalskag          | Qalqaq                      | Qalqaq                      |
| 183 | Kaltag           | Ggaał Doh                   | Ggaał Doh                   |
| 186 | Karluk           | Kal’ut                      | Kal’ut                      |
| 187 | Kasaan           | Gasa'áan                    | Gasa'áan                    |
| 190 | Kasigluk         | Kassigluq                   | Kassigluq                   |
| 193 | Kenai            | Shk'ituk't                  | Shk'ituk't                  |
| 196 | Ketchikan        | Kichx̱áan                    | Kichx̱áan                    |
| 197 | Kiana            | Katyaaq                     | Katyaaq                     |
| 200 | King Island      | Ugiuvak                     | Ugiuvak                     |
| 202 | Kipnuk           | Qipnek                      | Qipnek                      |
| 203 | Kivalina         | Kivaliñiq                   | Kivaliñiq                   |
| 205 | Klawock          | Lawaak                      | Lawaak                      |
| 207 | Klukwan          | Tlákw.aan                   | Tlákw.aan                   |
| 209 | Kobuk            | Laugviik                    | Laugviik                    |
| 211 | Kokhanok         | Qarr’unaq                   | Qarr’unaq                   |
| 212 | Kokrines         | Łoyh Denlekk’es Denh        | Łoyh Denlekk’es Denh        |
| 213 | Koliganek        | Qalirneq                    | Qalirneq                    |
| 214 | Kongiganak       | Kangirnaq                   | Kangirnaq                   |
| 215 | Kotlik           | Qerrulliik                  | Qerrulliik                  |
| 216 | Kotzebue         | Qikiqtaġruk                 | Qikiqtaġruk                 |
| 217 | Koyuk            | Kuuyuk                      | Kuuyuk                      |
| 218 | Koyukuk          | Meneelghaadze’ T’oh         | Meneelghaadze’ T’oh         |
| 220 | Kustatan         | Qezdeghnen                  | Qezdeghnen                  |
| 222 | Kwethluk         | Kuiggluk                    | Kuiggluk                    |
| 223 | Kwigillingok     | Kuigilnguq                  | Kuigilnguq                  |
| 225 | Lake Minchumina  | Menchuh Mene’               | Menchuh Mene’               |
| 226 | Larsen Bay       | Uyaqsaq                     | Uyaqsaq                     |
| 231 | Levelock         | Liivlek                     | Liivlek                     |
| 233 | Lime Village     | Hekdichen Hdakaq'           | Hekdichen Hdakaq'           |
| 236 | Lower Kalskag    | Qalqaq                      | Qalqaq                      |
| 237 | Lower Tonsina    | Kentsii Cae'e               | Kentsii Cae'e               |
| 239 | Manley           | Too Naaleł Denh             | Too Naaleł Denh             |
| 240 | Manokotak        | Manuquutaq                  | Manuquutaq                  |
| 241 | Mansfield        | Dihthâad                    | Dihthâad                    |
| 242 | Marshall         | Masserculleq                | Masserculleq                |
| 246 | McGrath          | Tochak’                     | Tochak’                     |
| 250 | Mekoryuk         | Mikuryar                    | Mikuryar                    |
| 252 | Mentasta         | Mendaesde                   | Mendaesde                   |
| 253 | Metlakatla       | Maxłakxaała                 | Maxłakxaała                 |
| 259 | Mountain Village | Asaacaryaraq                | Asaacaryaraq                |
| 261 | Nabesna          | Naambia Niign Daacheeg      | Naambia Niign Daacheeg      |
| 263 | Naknek           | Nakniq                      | Nakniq                      |
| 266 | Napakiak         | Naparyarraq                 | Naparyarraq                 |
| 268 | Napaskiak        | Napaskiaq                   | Napaskiaq                   |
| 271 | Nelson Lagoon    | Niilsanam Alĝuudaa          | Niilsanam Alĝuudaa          |
| 272 | Nenana           | Toghotili                   | Toghotili                   |
| 274 | New Stuyahok     | Cetuyaraq                   | Cetuyaraq                   |
| 275 | Newhalen         | Nuuriileng                  | Nuuriileng                  |
| 276 | Newtok           | Niugtaq                     | Niugtaq                     |
| 277 | Nightmute        | Negtemiut                   | Negtemiut                   |
| 280 | Nikolai          | Nikolai                     | Nikolai                     |
| 284 | Noatak           | Nuataam Kuuŋa               | Nuataam Kuuŋa               |
| 285 | Nome             | Sitŋasuaq                   | Sitŋasuaq                   |
| 286 | Nondalton        | Nundaltin                   | Nundaltin                   |
| 287 | Noorvik          | Nuurvik                     | Nuurvik                     |
| 289 | Northway         | K’ehtthiign                 | K’ehtthiign                 |
| 292 | Nuiqsut          | Nuiqsat                     | Nuiqsat                     |
| 293 | Nulato           | Noolaaghe Doh               | Noolaaghe Doh               |
| 295 | Nunapitchuk      | Nunapicuar                  | Nunapicuar                  |
| 297 | Ohogamiut        | Urr'agmiut                  | Urr'agmiut                  |
| 298 | Old Harbor       | Nuniaq                      | Nuniaq                      |
| 299 | Old Minto        | Menhti Xwghotthit           | Menhti Xwghotthit           |
| 301 | Oscarville       | Kuiggayagaq                 | Kuiggayagaq                 |
| 303 | Ouzinkie         | Uusenkaa                    | Uusenkaa                    |
| 310 | Pelican          | K'udeis'x̱'e                 | K'udeis'x̱'e                 |
| 312 | Perryville       | Perry-q                     | Perry-q                     |
| 313 | Petersburg       | Séet Ká                     | Séet Ká                     |
| 316 | Pilot Point      | Agisaq                      | Agisaq                      |
| 317 | Pilot Station    | Tuutalgaq                   | Tuutalgaq                   |
| 318 | Pitkas Point     | Negeqliim Painga            | Negeqliim Painga            |
| 319 | Platinum         | Arviiq                      | Arviiq                      |
| 321 | Point Hope       | Tikiġaq                     | Tikiġaq                     |
| 322 | Point Lay        | Kali                        | Kali                        |
| 327 | Port Graham      | Paluwik                     | Paluwik                     |
| 328 | Port Heiden      | Masrriq                     | Masrriq                     |
| 329 | Port Lions       | Masiqsirraq                 | Masiqsirraq                 |
| 337 | Quinhagak        | Kuinerraq                   | Kuinerraq                   |
| 339 | Rampart          | Dleł Taaneets               | Dleł Taaneets               |
| 342 | Ruby             | Tl'aa'ologhe                | Tl'aa'ologhe                |
| 343 | Russian Mission  | Iqugmiut                    | Iqugmiut                    |
| 345 | St. Mary’s       | Negeqliq                    | Negeqliq                    |
| 346 | St. Michael      | Taciq                       | Taciq                       |
| 349 | Salcha           | Soł Chaget                  | Soł Chaget                  |
| 354 | Savoonga         | Sivunga                     | Sivunga                     |
| 356 | Scammon Bay      | Marayaarmiut                | Marayaarmiut                |
| 358 | Seldovia         | Angagkitaqnuuq              | Angagkitaqnuuq              |
| 359 | Seward           | Qutalleq                    | Qutalleq                    |
| 360 | Shageluk         | Edixi                       | Edixi                       |
| 361 | Shaktoolik       | Saktuliq                    | Saktuliq                    |
| 363 | Shishmaref       | Qigiqtaq                    | Qigiqtaq                    |
| 365 | Sitka            | Sheet'ká                    | Sheet'ká                    |
| 368 | Slana            | Stl’aa Caegge               | Stl’aa Caegge               |
| 370 | Sleetmute        | Cellitemiut                 | Cellitemiut                 |
| 373 | South Naknek     | Qinuyang                    | Qinuyang                    |
| 377 | Stebbins         | Tapraq                      | Tapraq                      |
| 379 | Stevens Village  | Denyeet                     | Denyeet                     |
| 389 | Tanana           | Hohudodetlaatl Denh         | Hohudodetlaatl Denh         |
| 390 | Tatitlek         | Taatiilaaq                  | Taatiilaaq                  |
| 393 | Telida           | Tilayadi                    | Tilayadi                    |
| 394 | Teller           | Tala                        | Tala                        |
| 397 | Tetlin           | Teełąy                      | Teełąy                      |
| 402 | Togiak           | Tuyuryaq                    | Tuyuryaq                    |
| 405 | Toksook Bay      | Nunakauyaq                  | Nunakauyaq                  |
| 408 | Tuluksak         | Tuulkessaaq                 | Tuulkessaaq                 |
| 409 | Tuntutuliak      | Tuntutuliaq                 | Tuntutuliaq                 |
| 410 | Tununak          | Tununeq                     | Tununeq                     |
| 411 | Twin Hills       | Ingricuar                   | Ingricuar                   |
| 413 | Tyonek           | Qaggeyshlat                 | Qaggeyshlat                 |
| 414 | Ugashik          | Ugaasaq                     | Ugaasaq                     |
| 419 | Unalakleet       | Uŋalaqłiit                  | Uŋalaqłiit                  |
| 426 | Valdez           | Suacit                      | Suacit                      |
| 427 | Venetie          | Vįįhtąįį                    | Vįįhtąįį                    |
| 428 | Wainwright       | Ulġuniq                     | Ulġuniq                     |
| 429 | Wales            | Kiŋigin                     | Kiŋigin                     |
| 433 | White Mountain   | Nasirvik                    | Nasirvik                    |
| 439 | Wrangell         | Shtax’héen                  | Shtax’héen                  |
| 440 | Yakutat          | Yaakwdáat                   | Yaakwdáat                   |

**Comment by MikeDelue** [comment]
@charparr Incorrect. In all instances alt_name from the .xlsx or .csv in my email is the correct version of the name, regardless of whether B = H is true or not. H is the correct list now including 1 - Unchanged alt_name fields, 2 - new/edited alt_name fields, and 3 - alt_name fields which used to contain data and now are empty.

**Comment by charparr** [comment]
Closed via #49
