### ISSUE TITLE
Add Fort Davis

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/geospatial-vector-veracity#3]
Fort Davis, AK 64.48, -165.42

**Comment by brucecrevensten** [comment]
So I think this one came from a spreadsheet that we developed back in ~Feb for the HSIAA, but in practice this may not be a great one to include -- it's basically atop Nome (for the scale of our data) and was abandoned a long time ago.

I suggest we do the opposite of this ticket and remove it.  @kyleredilla @charparr @MikeDelue agree?

**Comment by MikeDelue** [comment]
> So I think this one came from a spreadsheet that we developed back in ~Feb for the HSIAA, but in practice this may not be a great one to include -- it's basically atop Nome (for the scale of our data) and was abandoned a long time ago.
> 
> I suggest we do the opposite of this ticket and remove it. @kyleredilla @charparr @MikeDelue agree?

While a utility for adding more in the future does make sense given the current extent of the list, I agree that in this case removal > fixing and adding this location.
