### ISSUE TITLE
Simplify Protected Area Polygons

### ISSUE THREAD

**Issue by charparr** [ua-snap/geospatial-vector-veracity#38]
- Merge park and refuges where appropriate, but retain the individual parts. Ask J. Little for data where needed. Possibly add flag for "simplified"
 - Fill polygon holes for allotments and other private holdings.
 - Flag dispersed / discontinuous polygons.
 -

**Comment by brucecrevensten** [comment]
@charparr For this, could you maybe send Jeremy the updated version of this shape file so he can review it and make sure it seems correct to him?  I'll reopen it for now in case there's further work, but if no further action is needed it can be closed.

**Comment by charparr** [comment]
Yup! I'll _shoomp_ those over to Jeremy and add any feedback I receive here.

**Comment by charparr** [comment]
These polygons have been out in the wild in the NCR beta for a couple months without any issues being raised. We'll continue to monitor, but I think the simplifying work we've done has satisfied JL and AB so I'm closing this issue. We can open issues on an ad hoc basis later on if we get feedback on a certain protected area.
