### ISSUE TITLE
Check for points which fall within a small grid cell (1km) and deduplicate if so

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/geospatial-vector-veracity#42]
The idea here is to see if have two names for essentially the same place; if so, pick the more common/familiar name.  This just reduces the number of items we list and maintain and people need to choose from.

**Comment by charparr** [comment]
|    id   |                 name                |            alt_name           |           nearest_neighbor          |   distance_km   |
|:-------:|:-----------------------------------:|:-----------------------------:|:-----------------------------------:|:---------------:|
| :------ | :---------------------------------- | :---------------------------- | :---------------------------------- | --------------: |
|   AK40  |             Bill Moores             |              nan              |               Hamilton              |       0.1       |
|  AK144  |               Hamilton              |              nan              |             Bill Moores             |       0.1       |
|  AK417  |            Upper Kalskag            |              nan              |               Kalskag               |       0.2       |
|  AK249  |             Meyers Chuck            |              nan              |             Myers Chuck             |       0.2       |
|  AK178  |               Kalskag               |             Qalqaq            |            Upper Kalskag            |       0.2       |
|  AK255  |             Myers Chuck             |              nan              |             Meyers Chuck            |       0.2       |
|  AK195  |             King Island             |            Ugiuvak            |                Ukivok               |       0.3       |
|   AK17  |              Andreafsky             |              nan              |             Saint Mary's            |       0.3       |
|  AK206  |               Kokhanok              |           Qarr’unaq           |               Kakhonak              |       0.3       |
|  AK175  |               Kakhonak              |              nan              |               Kokhanok              |       0.3       |
|   AK47  |            Brevig Mission           |            Sitaisaq           |            Teller Mission           |       0.3       |
|  AK391  |            Teller Mission           |              nan              |            Brevig Mission           |       0.3       |
|  AK410  |                Ukivok               |              nan              |             King Island             |       0.3       |
|  AK340  |             Saint Mary's            |            Negeqliq           |              Andreafsky             |       0.3       |
|   AK37  |               Bettles               |  Kk’odlel T’odegheelenh Denh  |              Evansville             |       0.6       |
|  AK121  |              Evansville             |              nan              |               Bettles               |       0.6       |
|  AK259  |               Nanwalek              |              nan              |             English Bay             |       0.6       |
|  AK118  |             English Bay             |            Nanwalek           |               Nanwalek              |       0.6       |
|  AK364  |             Slaterville             |              nan              |                Lemeta               |       0.7       |
|  AK224  |                Lemeta               |              nan              |             Slaterville             |       0.7       |
|   AK59  |         Charlieskin Village         |              nan              |               Kathakne              |       0.8       |
|  AK187  |               Kathakne              |              nan              |         Charlieskin Village         |       0.8       |
|   AK34  |               Belmezok              |              nan              |                Wales                |        1        |
|  AK424  |                Wales                |            Kiŋigin            |               Belmezok              |        1        |
|  AK260  |              Napaimiut              |              nan              |              Napamiute              |        1        |
|  AK262  |              Napamiute              |              nan              |              Napaimiut              |        1        |
|  AK453  |  Joe Mace Island State Marine Park  |              nan              |             Point Baker             |       1.1       |
|   AK1   |               Afognak               |            Agw’aneq           |            Aleut Village            |       1.1       |
|  AK425  |              Ward Cove              |              nan              |             Refuge Cove             |       1.1       |
|   AK9   |            Aleut Village            |              nan              |               Afognak               |       1.1       |
|  AK315  |             Point Baker             |              nan              |  Joe Mace Island State Marine Park  |       1.1       |
|  AK336  |             Refuge Cove             |              nan              |              Ward Cove              |       1.1       |
|  AK283  |              North Pole             |              nan              |            Highland Park            |       1.3       |
|  AK117  |               Emmonak               |            Imangaq            |                Kwiguk               |       1.3       |
|  AK148  |            Highland Park            |              nan              |              North Pole             |       1.3       |
|  AK219  |                Kwiguk               |              nan              |               Emmonak               |       1.3       |
|  AK441  |        Eareckson Air Station        |              nan              |            Shemya Station           |       1.4       |
|  AK357  |            Shemya Station           |              nan              |        Eareckson Air Station        |       1.4       |
|  AK119  |                 Eska                |              nan              |              Jonesville             |       1.6       |
|  AK171  |              Jonesville             |              nan              |                 Eska                |       1.6       |
|   AK16  |               Anderson              |              nan              |                Clear                |       1.6       |
|   AK81  |                Clear                |              nan              |               Anderson              |       1.6       |
|  AK258  |                Naknek               |             Nakniq            |             South Naknek            |       1.7       |
|  AK368  |             South Naknek            |            Qinuyang           |                Naknek               |       1.7       |
|  AK124  |              Fairbanks              |              nan              |             Slaterville             |       1.7       |
|  AK101  |             Dutch Harbor            |              nan              |               Unalaska              |        2        |
|  AK306  |            Pennock Island           |              nan              |              Ketchikan              |        2        |
|  AK415  |               Unalaska              |            Iluulux̂            |             Dutch Harbor            |        2        |
|  AK313  |             Pitkas Point            |        Negeqliim Painga       |              St. Mary's             |        2        |
|  AK225  |              Lena Beach             |              nan              |              Tee Harbor             |        2        |
|  AK371  |              St. Mary's             |              nan              |             Pitkas Point            |        2        |
|  AK388  |              Tee Harbor             |              nan              |              Lena Beach             |        2        |
|  AK191  |              Ketchikan              |            Kichx̱áan           |            Pennock Island           |        2        |
|  AK350  |                Saxman               |              nan              |            Pennock Island           |       2.3       |
|  AK296  |              Oscarville             |          Kuiggayagaq          |              Napaskiak              |       2.5       |
|         |                                     |                               |                                     |                 |

**Comment by charparr** [comment]
See change tracking spreadsheet: https://docs.google.com/spreadsheets/d/16ImO2bBqPnqtyYnJljBWnQJ3745zkqrszgIBwyERTdk/edit?usp=sharing

**Comment by charparr** [comment]
Closed by #59
