### ISSUE TITLE
Update Github Action to refresh production URL

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/geospatial-vector-veracity#45]
Currently, we have a Github Action that on every push to this directory, the API will update the CSVs, shapefiles, and JSONs generated from this repository. This is pointed at http://cache.earthmaps.io/update currently, but when everything is merged into main and in production, we need to change https://github.com/ua-snap/geospatial-vector-veracity/blob/58b5778c7cf858627c0ca6ad6ab80d8ad2218380/.github/workflows/refresh_api.yaml#L10 to https://earthmaps.io/update

**Comment by charparr** [comment]
Closed by #66
