### ISSUE TITLE
What is this place / bounds? 

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/geospatial-vector-veracity#75]
There's a protected area labeled "Major Military" that seems to fail, i.e. http://localhost:3000/report/protected_area/DODDOE1#results

...what's this place?  What's its outline?  Is this accurate / should this exist in our vector lib?

**Comment by charparr** [comment]
Move to cull it. It is too broad, ambiguous, and discontinuous to be useful to us and likely others. There may be a polygon boundary set for military installations - but that is an effort for another day.
