### ISSUE TITLE
Determine if HUC 19030103 should be removed from HUC-8s

### ISSUE THREAD

**Issue by cstephen** [ua-snap/geospatial-vector-veracity#85]
The following API endpoints do not return data for HUC 19030103:

- Temperature
- Precipitation
- Permafrost
- Relative Flammability (ALFRESCO)
- Relative Vegetation Change (ALFRESCO)

This may be related to the fact that HUC 19030103 spans the antimeridian. If there is not an easy fix for this, we should remove HUC 19030103 from this repo.

**Comment by charparr** [comment]
In my opinion this "Western Aleutian Islands" HUC is not a useful "data cookie cutter" for our purposes. My preference would be to remove the HUC from our records. For the Aleutians in general point queries will be most representative vs. summarizing cross multiple different islands.
