### ISSUE TITLE
Reshape all polygons to be the intersection of the polygon and our data domain

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/geospatial-vector-veracity#92]
We keep encountering polygons that fail in the app because there's no data.  Instead of fixing this on an ad-hoc basis, I suggest that we reshape every polygon in the app to be the intersection of the polygon and our data domain (we can intersect with the IEM domain even though we know that won't include permafrost everywhere).

Xref #91

**Comment by charparr** [comment]
That makes sense - so like this example using the native corporations? Black lines are the original and the colored polygons are the intersection with the "IEM with AK Aleutians" domain. 
![image](https://user-images.githubusercontent.com/7774271/165343603-f48d6f8c-76a1-4b71-aae9-b5c28f3bdc6e.png)

**Comment by charparr** [comment]
I recommend closing this issue - our data domain is nebulous and ever-changing and full of odd gaps and holes. We have more sophisticated ways to deal with no-data in certain areas now.
