### ISSUE TITLE
Adjust polygons to work better with the antemeridian?

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/geospatial-vector-veracity#93]
Right now we've got code in the client app that adjusts points that are west of the antemeridian (i.e. 175 becomes -185) but could/should that be done on this end, not in the client?

**Comment by charparr** [comment]
If we execute #92 that would make it such all polygons are limited to the following extent:
```
{'minx': -178.225139,
 'miny': 51.34921302,
 'maxx': 179.7607474,
 'maxy': 71.3907203}
 ```

**Comment by charparr** [comment]
Closing - we now have better ways of handling partial or complete no data responses for polygon queries. We don't, and probably shouldn't, modify the data cookie cutters just because we ran out of cookie dough.
