### ISSUE TITLE
Add GH action for staging API

### ISSUE THREAD

**Issue by kyleredilla** [ua-snap/geospatial-vector-veracity#95]
We will need a GH action for production instance (and staging?) when ready. Correct if this isn't quite right.

**Comment by BobTorgerson** [comment]
We want to have a GitHub Action that automatically runs the /update endpoint on the development (staging) API as well as the production API which is already running as an action.

**Comment by brucecrevensten** [comment]
@BobTorgerson @cstephen is this ticket invalid now with some stuff moving to Geoserver?

**Comment by BobTorgerson** [comment]
This is no longer a valid ticket since we modified our way of interacting with the search and polygon retrieval
